version: "3.8"

services:
  db:
    container_name: db-game
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "9000:3306"
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_USER: app_db
      MYSQL_PASSWORD: example
  phpmyadmin:
    image: phpmyadmin
    restart: always
    depends_on:
      - db
    ports:
      - "8080:80"
